name: Run tests

# Description:
# - This workflow runs tests on the codebase, fails if tests do not pass.
# - Tests are run on both Windows and Ubuntu to ensure cross-platform compatibility for development.

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup PostgresSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          database: ae_test
          port: 5432
          username: postgres
          password: postgres

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Setup database for tests
        run: pnpm workflow:init_db

      - name: Run tests
        run: pnpm workflow:test
        env:
          POSTGRES_DB: ae_test
          POSTGRES_HOST: '127.0.0.1'
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DEBUG: true
          EMAIL_ENABLED: false
          JWT_KEY: jwt_key

      - name: Export coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Coverage results (${{ matrix.os }})
          path: ./coverage
          retention-days: 7
