# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: PR/Push update

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  testing:
    needs: linting
    if: ${{ needs.linting.result == 'success' }}
    uses: ./.github/workflows/testing.yml

  analyzing:
    needs: testing
    if: ${{ needs.testing.result == 'success' }}
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
